orun: main.o Fcurv.o
	g++ main.o Fcurv.o -o run

test: test.0 Fcurv.o
	g++ test.o Fcurv.o

main.o: main.cc
	g++ -c main.cc

Fcurv.o: Fcurv.cc
	g++ -c Fcurv.cc

test.o: test.cc
	g++ -c test.cc

clean:
	rm *.o test run

